// Generated By: Claude Code (Claude Opus 4.7)
namespace NINA.Plugin.PrometheusExporter
{
    /// <summary>
    /// Cross-cutting constants for the plugin. Default option values, label keys, bind aliases,
    /// status sentinels, and shared "unknown" filler. Metric NAMES live in <see cref="MetricNames"/>.
    /// </summary>
    internal static class Constants
    {
        // ---- Plugin identity ----
        public const string PluginInstallTitle = "Prometheus Exporter";

        // ---- Option defaults ----
        public const int DefaultPort = 9876;
        public const string DefaultBindAddress = "127.0.0.1";
        public const int DefaultSequencePollIntervalSeconds = 1;
        public const int DefaultAfTimeoutMinutes = 10;

        // ---- Option bounds ----
        public const int PortMin = 1;
        public const int PortMax = 65535;
        public const int SequencePollSecondsMin = 1;
        public const int SequencePollSecondsMax = 60;
        public const int AfTimeoutMinutesMin = 0;
        public const int AfTimeoutMinutesMax = 120;

        // ---- Bind-address normalization ----
        // Any of these incoming values get translated to EmbedIO's all-interfaces host wildcard.
        public const string BindAllIpv4 = "0.0.0.0";
        public const string BindAllHttpListener = "+";
        public const string BindAllEmbedIo = "*";

        // ---- Default labels (applied to every metric via MetricFactory) ----
        public const string LabelProfileName = "profile_name";
        public const string LabelHostName = "host_name";

        // ---- Common extra labels ----
        public const string LabelType = "type";
        public const string LabelId = "id";
        public const string LabelName = "name";
        public const string LabelFilter = "filter";
        public const string LabelFilterName = "filter_name";
        public const string LabelCategory = "category";
        public const string LabelItem = "item";
        public const string LabelMethod = "method";
        public const string LabelFitting = "fitting";
        public const string LabelBacklashIn = "backlash_in";
        public const string LabelBacklashOut = "backlash_out";
        public const string LabelBacklashModel = "backlash_model";
        public const string LabelFitType = "type"; // semantic distinction from LabelType: fit-type vs equipment-type
        public const string LabelReason = "reason";
        public const string LabelExposureTimeSeconds = "exposure_time_s";
        public const string LabelGain = "gain";
        public const string LabelOffset = "offset";
        public const string LabelBinning = "binning";

        // ---- Equipment "type" label values (nina_equipment{type=...}) ----
        public const string TypeCamera = "camera";
        public const string TypeTelescope = "telescope";
        public const string TypeFocuser = "focuser";
        public const string TypeFilterWheel = "filterwheel";
        public const string TypeGuider = "guider";
        public const string TypeDome = "dome";
        public const string TypeRotator = "rotator";
        public const string TypeFlatDevice = "flat_device";
        public const string TypeSafetyMonitor = "safety_monitor";
        public const string TypeWeather = "weather";
        public const string TypeSwitch = "switch";

        // ---- Filler label value when source field is missing or null ----
        public const string Unknown = "unknown";

        // ---- AutoFocus failure reasons (nina_autofocus_failure_total{reason=...}) ----
        public const string AfFailureTimeout = "timeout";

        // ---- Server status sentinels ----
        public const string StatusStopped = "stopped";
        public const string StatusStarting = "starting";

        // ---- Filesystem ----
        public const string NinaAutoFocusSubdir = @"NINA\AutoFocus";
        public const string AutoFocusJsonFilter = "*.json";
        public const int AutoFocusWatcherDebounceMs = 200;
        public const int ServerStartProbeTimeoutSeconds = 3;
        public const int ServerStartProbeIntervalMs = 50;
    }
}
