// Generated By: Claude Code (Claude Opus 4.7)
using System.ComponentModel.Composition;
using System.Windows;

namespace NINA.Plugin.PrometheusExporter;


[Export(typeof(ResourceDictionary))]
public partial class Options : ResourceDictionary
{

    public Options()
    {
        InitializeComponent();
    }
}
