// Generated By: Claude Code (Claude Opus 4.7)
using NINA.Core.Utility;
using NINA.Profile;
using NINA.Profile.Interfaces;
using System;

namespace NINA.Plugin.PrometheusExporter
{

    public partial class PrometheusExporterOptions : BaseINPC
    {
        private readonly IProfileService _profileService;
        private readonly PluginOptionsAccessor _accessor;

        public PrometheusExporterOptions(IProfileService profileService)
        {
            _profileService = profileService;
            var guid = PluginOptionsAccessor.GetAssemblyGuid(typeof(PrometheusExporterPlugin))
                ?? throw new InvalidOperationException("Plugin assembly GUID not found");
            _accessor = new PluginOptionsAccessor(profileService, guid);
        }

        public int Port
        {
            get => _accessor.GetValueInt32(nameof(Port), 9876);
            set { _accessor.SetValueInt32(nameof(Port), Clamp(value, 1, 65535)); RaisePropertyChanged(); }
        }

        public string BindAddress
        {
            get => _accessor.GetValueString(nameof(BindAddress), "0.0.0.0");
            set { _accessor.SetValueString(nameof(BindAddress), string.IsNullOrWhiteSpace(value) ? "0.0.0.0" : value); RaisePropertyChanged(); }
        }

        public int SequencePollIntervalSeconds
        {
            get => _accessor.GetValueInt32(nameof(SequencePollIntervalSeconds), 1);
            set { _accessor.SetValueInt32(nameof(SequencePollIntervalSeconds), Clamp(value, 1, 60)); RaisePropertyChanged(); }
        }

        public int AfTimeoutMinutes
        {
            get => _accessor.GetValueInt32(nameof(AfTimeoutMinutes), 10);
            set { _accessor.SetValueInt32(nameof(AfTimeoutMinutes), Clamp(value, 0, 120)); RaisePropertyChanged(); }
        }

        private string _serverStatus = "stopped";
        public string ServerStatus
        {
            get => _serverStatus;
            internal set { _serverStatus = value; RaisePropertyChanged(); }
        }

        private static int Clamp(int v, int lo, int hi) => v < lo ? lo : (v > hi ? hi : v);
    }
}
