// Generated By: Claude Code (Claude Opus 4.7)
using EmbedIO;
using EmbedIO.Actions;
using NINA.Core.Utility;
using Prometheus;
using System;
using System.IO;
using System.Net;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace NINA.Plugin.PrometheusExporter
{

    // HTTP transport. EmbedIO with HttpListenerMode.EmbedIO uses a pure-managed socket listener
    // (not System.Net.HttpListener / http.sys), so binding non-loopback addresses works without
    // admin or a `netsh http add urlacl` grant. Pattern lifted from ~/source/ninaAPI/.
    internal class PrometheusServer
    {
        private WebServer? _server;
        private CancellationTokenSource? _cts;
        private Thread? _serverThread;
        public string Status { get; private set; } = "stopped";

        public virtual void Start(string bindAddress, int port)
        {
            // EmbedIO accepts hostname-style prefixes. For all-interfaces use "*"; for a specific
            // address use that address verbatim. Normalize the typical aliases to "*".
            var listenerHost = (bindAddress == "0.0.0.0" || bindAddress == "+" || string.IsNullOrWhiteSpace(bindAddress))
                ? "*"
                : bindAddress;
            var prefix = $"http://{listenerHost}:{port}/";

            try
            {
                _cts = new CancellationTokenSource();
                _server = new WebServer(o => o
                    .WithUrlPrefix(prefix)
                    .WithMode(HttpListenerMode.EmbedIO))
                    .WithAction("/metrics", HttpVerbs.Get, async ctx =>
                    {
                        ctx.Response.ContentType = "text/plain; version=0.0.4; charset=utf-8";
                        using var ms = new MemoryStream();
                        await Metrics.DefaultRegistry.CollectAndExportAsTextAsync(ms, ctx.CancellationToken);
                        var body = Encoding.UTF8.GetString(ms.ToArray());
                        await ctx.SendStringAsync(body, "text/plain", Encoding.UTF8);
                    });

                var srv = _server;
                var tok = _cts.Token;
                _serverThread = new Thread(() =>
                {
                    try { srv.RunAsync(tok).GetAwaiter().GetResult(); }
                    catch (OperationCanceledException) { /* expected on Stop */ }
                    catch (Exception ex) { Logger.Error($"PrometheusServer: RunAsync threw: {ex}"); }
                })
                { Name = "PrometheusExporter HTTP", IsBackground = true };
                _serverThread.Start();

                Status = $"running on {bindAddress}:{port}";
                Logger.Info($"PrometheusServer: {Status} (EmbedIO managed listener)");
            }
            catch (HttpListenerException ex)
            {
                // Should be unreachable under HttpListenerMode.EmbedIO, but kept for defense in depth.
                Status = $"failed: HttpListener {ex.ErrorCode} — {ex.Message}";
                Logger.Error($"PrometheusServer start failed: {ex}");
            }
            catch (Exception ex)
            {
                Status = $"failed: {ex.Message}";
                Logger.Error($"PrometheusServer start failed: {ex}");
            }
        }

        public virtual void Stop()
        {
            try
            {
                _cts?.Cancel();
                _server?.Dispose();
            }
            catch (Exception ex)
            {
                Logger.Error($"PrometheusServer stop failed: {ex}");
            }
            finally
            {
                _server = null;
                _cts?.Dispose();
                _cts = null;
                _serverThread = null;
                Status = "stopped";
            }
        }

        public virtual void Restart(string bindAddress, int port)
        {
            Stop();
            Start(bindAddress, port);
        }
    }
}
