// Generated By: Claude Code (Claude Opus 4.7)
using EmbedIO;
using EmbedIO.Actions;
using NINA.Core.Utility;
using Prometheus;
using System;
using System.IO;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace NINA.Plugin.PrometheusExporter
{

    // HTTP transport. EmbedIO with HttpListenerMode.EmbedIO uses a pure-managed socket listener
    // (not System.Net.HttpListener / http.sys), so binding non-loopback addresses works without
    // admin or a `netsh http add urlacl` grant. Pattern lifted from ~/source/ninaAPI/.
    internal class PrometheusServer
    {
        private WebServer? _server;
        private CancellationTokenSource? _cts;
        private Task? _runTask;
        private string _status = Constants.StatusStopped;

        public string Status
        {
            get => _status;
            private set
            {
                if (_status == value) return;
                _status = value;
                StatusChanged?.Invoke(this, EventArgs.Empty);
            }
        }

        public event EventHandler? StatusChanged;

        public virtual void Start(string bindAddress, int port)
        {
            // EmbedIO accepts hostname-style prefixes. For all-interfaces use "*"; for a specific
            // address use that address verbatim. Normalize the typical aliases to "*".
            var listenerHost = (bindAddress == Constants.BindAllIpv4 || bindAddress == Constants.BindAllHttpListener || string.IsNullOrWhiteSpace(bindAddress))
                ? Constants.BindAllEmbedIo
                : bindAddress;
            var prefix = $"http://{listenerHost}:{port}/";

            try
            {
                _cts = new CancellationTokenSource();
                _server = new WebServer(o => o
                    .WithUrlPrefix(prefix)
                    .WithMode(HttpListenerMode.EmbedIO))
                    .WithAction("/metrics", HttpVerbs.Get, async ctx =>
                    {
                        ctx.Response.ContentType = "text/plain; version=0.0.4; charset=utf-8";
                        using var ms = new MemoryStream();
                        await Metrics.DefaultRegistry.CollectAndExportAsTextAsync(ms, ctx.CancellationToken);
                        await ctx.SendStringAsync(Encoding.UTF8.GetString(ms.ToArray()), "text/plain", Encoding.UTF8);
                    });

                Status = Constants.StatusStarting;
                _runTask = _server.RunAsync(_cts.Token);

                // Probe for a result: either RunAsync faulted (bind failed) or the server reached Listening.
                // EmbedIO's HttpListenerMode.EmbedIO surfaces SocketException via RunAsync's task when
                // the underlying TcpListener.Start() fails (port in use, bind address invalid, etc.).
                var deadline = DateTime.UtcNow.AddSeconds(Constants.ServerStartProbeTimeoutSeconds);
                while (DateTime.UtcNow < deadline)
                {
                    if (_runTask.IsFaulted)
                    {
                        var ex = _runTask.Exception?.InnerException;
                        Status = $"failed: {ex?.Message ?? _runTask.Exception?.Message ?? Constants.Unknown}";
                        Logger.Error($"PrometheusServer start failed: {_runTask.Exception}");
                        return;
                    }
                    if (_runTask.IsCompleted)
                    {
                        Status = "stopped (server returned immediately)";
                        return;
                    }
                    if (_server.State == WebServerState.Listening)
                    {
                        Status = $"running on {bindAddress}:{port}";
                        Logger.Info($"PrometheusServer: {Status} (EmbedIO managed listener)");
                        return;
                    }
                    Thread.Sleep(Constants.ServerStartProbeIntervalMs);
                }
                // Timeout — server never reached Listening within the deadline.
                Status = $"unknown: server state is {_server.State} after probe timeout";
                Logger.Warning($"PrometheusServer: {Status}");
            }
            catch (Exception ex)
            {
                Status = $"failed: {ex.Message}";
                Logger.Error($"PrometheusServer start failed: {ex}");
            }
        }

        public virtual void Stop()
        {
            try
            {
                _cts?.Cancel();
                _server?.Dispose();
            }
            catch (Exception ex)
            {
                Logger.Error($"PrometheusServer stop failed: {ex}");
            }
            finally
            {
                _server = null;
                _cts?.Dispose();
                _cts = null;
                _runTask = null;
                Status = Constants.StatusStopped;
            }
        }

        public virtual void Restart(string bindAddress, int port)
        {
            Stop();
            Start(bindAddress, port);
        }
    }
}
