// Generated By: Claude Code (Claude Opus 4.7)
using NINA.Plugin.PrometheusExporter.Stream;
using System.Collections.Generic;
using Xunit;

namespace NINA.Plugin.PrometheusExporter.Tests {

    public class AutoFocusStateMachineTests {

        private sealed class Capture {
            public readonly List<bool> Running = new();
            public readonly List<string> Successes = new();
            public readonly List<string> Failures = new();
            public AutoFocusStateMachine Build() =>
                new AutoFocusStateMachine(b => Running.Add(b), f => Successes.Add(f), r => Failures.Add(r));
        }

        [Fact]
        public void Idle_Start_TransitionsToRunning() {
            var c = new Capture(); var sm = c.Build();
            sm.Start();
            Assert.True(sm.IsRunning);
            Assert.Equal(new[] { true }, c.Running);
        }

        [Fact]
        public void Running_End_TransitionsToIdleAndCountsSuccess() {
            var c = new Capture(); var sm = c.Build();
            sm.Start();
            sm.End("L");
            Assert.False(sm.IsRunning);
            Assert.Equal(new[] { true, false }, c.Running);
            Assert.Single(c.Successes);
            Assert.Equal("L", c.Successes[0]);
            Assert.Empty(c.Failures);
        }

        [Fact]
        public void Running_Timeout_CountsFailureNotSuccess() {
            var c = new Capture(); var sm = c.Build();
            sm.Start();
            sm.Timeout();
            Assert.False(sm.IsRunning);
            Assert.Single(c.Failures);
            Assert.Equal("timeout", c.Failures[0]);
            Assert.Empty(c.Successes);
        }

        [Fact]
        public void Idle_End_Ignored() {
            var c = new Capture(); var sm = c.Build();
            sm.End("L");
            Assert.Empty(c.Successes);
            Assert.Empty(c.Running);
        }

        [Fact]
        public void Idle_Timeout_Ignored() {
            var c = new Capture(); var sm = c.Build();
            sm.Timeout();
            Assert.Empty(c.Failures);
            Assert.Empty(c.Running);
        }

        [Fact]
        public void Running_DuplicateStart_Ignored() {
            var c = new Capture(); var sm = c.Build();
            sm.Start();
            sm.Start();
            Assert.Equal(new[] { true }, c.Running);
        }

        [Fact]
        public void Running_EndThenTimeout_TimeoutIgnored() {
            var c = new Capture(); var sm = c.Build();
            sm.Start();
            sm.End("L");
            sm.Timeout();
            Assert.Empty(c.Failures);
            Assert.Single(c.Successes);
        }
    }
}
