// Generated By: Claude Code (Claude Opus 4.7)
using Moq;
using NINA.Equipment.Interfaces.Mediator;
using NINA.Image.ImageData;
using NINA.Plugin.PrometheusExporter.Stream;
using NINA.Profile.Interfaces;
using NINA.WPF.Base.Interfaces.Mediator;
using Xunit;

namespace NINA.Plugin.PrometheusExporter.Tests {

    public class ImageMetricsTests {

        private static (MetricFactory, ImageMetrics) Build() {
            var profile = new Mock<IProfileService>();
            profile.Setup(p => p.ActiveProfile.Name).Returns("test");
            var factory = new MetricFactory(profile.Object);
            var med = new Mock<IImageSaveMediator>();
            var metrics = new ImageMetrics(factory, med.Object);
            return (factory, metrics);
        }

        [Fact]
        public void BuildExposureLabels_FromFullArgs_ProducesExpectedTuple() {
            var (_, metrics) = Build();
            var args = new ImageSavedEventArgs {
                Filter = "L",
                MetaData = new ImageMetaData {
                    Image = new ImageParameter { ExposureTime = 30.0, Binning = "1x1" },
                    Camera = new CameraParameter { Gain = 100, Offset = 50 }
                }
            };
            var labels = metrics.BuildExposureLabels(args);
            // labels: [profile_name, host_name, exposure_time_s, filter, gain, offset, binning]
            Assert.Equal("test", labels[0]);
            Assert.Equal("30.00", labels[2]);
            Assert.Equal("L", labels[3]);
            Assert.Equal("100", labels[4]);
            Assert.Equal("50", labels[5]);
            Assert.Equal("1x1", labels[6]);
        }

        [Fact]
        public void BuildExposureLabels_FromMissingMetadata_FallsBackToUnknown() {
            var (_, metrics) = Build();
            var args = new ImageSavedEventArgs();
            var labels = metrics.BuildExposureLabels(args);
            Assert.Equal("unknown", labels[2]);
            Assert.Equal("unknown", labels[3]);
            Assert.Equal("unknown", labels[4]);
            Assert.Equal("unknown", labels[5]);
            Assert.Equal("unknown", labels[6]);
        }
    }
}
