// Generated By: Claude Code (Claude Opus 4.7)
using Xunit;

namespace NINA.Plugin.PrometheusExporter.Tests;


public class Sanity
{
    [Fact]
    public void TestProjectBuilds() => Assert.True(true);
}
