// Generated By: Claude Code (Claude Opus 4.7)
using NINA.Plugin.PrometheusExporter.Stream;
using System.Collections.Generic;
using Xunit;

namespace NINA.Plugin.PrometheusExporter.Tests;


public class SequenceMetricsTests
{

    [Fact]
    public void Diff_AddTransition_OnlyInAdded()
    {
        var prev = new HashSet<(string, string)>();
        var curr = new HashSet<(string, string)> { ("Cat", "ItemA") };
        var (added, removed) = SequenceMetrics.Diff(prev, curr);
        Assert.Single(added);
        Assert.Empty(removed);
        Assert.Contains(("Cat", "ItemA"), added);
    }

    [Fact]
    public void Diff_RemoveTransition_OnlyInRemoved()
    {
        var prev = new HashSet<(string, string)> { ("Cat", "ItemA") };
        var curr = new HashSet<(string, string)>();
        var (added, removed) = SequenceMetrics.Diff(prev, curr);
        Assert.Empty(added);
        Assert.Single(removed);
        Assert.Contains(("Cat", "ItemA"), removed);
    }

    [Fact]
    public void Diff_NoChange_BothEmpty()
    {
        var prev = new HashSet<(string, string)> { ("Cat", "ItemA") };
        var curr = new HashSet<(string, string)> { ("Cat", "ItemA") };
        var (added, removed) = SequenceMetrics.Diff(prev, curr);
        Assert.Empty(added);
        Assert.Empty(removed);
    }

    [Fact]
    public void Diff_SimultaneousAddRemove_BothPopulated()
    {
        var prev = new HashSet<(string, string)> { ("Cat", "ItemA") };
        var curr = new HashSet<(string, string)> { ("Cat", "ItemB") };
        var (added, removed) = SequenceMetrics.Diff(prev, curr);
        Assert.Contains(("Cat", "ItemB"), added);
        Assert.Contains(("Cat", "ItemA"), removed);
    }
}
