// Generated By: Claude Code (Claude Opus 4.7)
using System;

namespace NINA.Plugin.PrometheusExporter.Stream
{

    internal sealed class AutoFocusStateMachine
    {
        private readonly Action<bool> _onRunningChanged;
        private readonly Action<string> _onSuccess;   // arg: filter
        private readonly Action<string> _onFailure;   // arg: reason
        private readonly object _lock = new();
        private bool _running;

        public AutoFocusStateMachine(
            Action<bool> onRunningChanged,
            Action<string> onSuccess,
            Action<string> onFailure)
        {
            _onRunningChanged = onRunningChanged;
            _onSuccess = onSuccess;
            _onFailure = onFailure;
        }

        public bool IsRunning
        {
            get { lock (_lock) { return _running; } }
        }

        public void Start()
        {
            lock (_lock)
            {
                if (_running) return;       // idempotent
                _running = true;
            }
            _onRunningChanged(true);
        }

        public void End(string filter)
        {
            lock (_lock)
            {
                if (!_running) return;
                _running = false;
            }
            _onRunningChanged(false);
            _onSuccess(filter);
        }

        public void Timeout()
        {
            lock (_lock)
            {
                if (!_running) return;
                _running = false;
            }
            _onRunningChanged(false);
            _onFailure(Constants.AfFailureTimeout);
        }
    }
}
