// Generated By: Claude Code (Claude Opus 4.7)
using NINA.Equipment.Equipment.MyDome;
using NINA.Equipment.Interfaces;
using NINA.Equipment.Interfaces.Mediator;
using Prometheus;
using System;

namespace NINA.Plugin.PrometheusExporter.Stream
{

    internal sealed class DomeMetrics : IMetricCollector, IDomeConsumer
    {
        private readonly MetricFactory _factory;
        private readonly IDomeMediator _mediator;

        private readonly Gauge _azimuth;
        private readonly Gauge _slewing;
        private readonly Gauge _atPark;
        private readonly Gauge _atHome;
        private readonly Gauge _shutterOpen;
        private readonly Gauge _shutterState;     // -1=None, 0=Open, 1=Closed, 2=Opening, 3=Closing, 4=Error (per ShutterState enum)

        public DomeMetrics(MetricFactory factory, IDomeMediator mediator)
        {
            _factory = factory;
            _mediator = mediator;
            var ln = _factory.LabelNames();
            _azimuth = Metrics.CreateGauge("nina_dome_azimuth_degrees", "Dome azimuth in degrees", new GaugeConfiguration { LabelNames = ln });
            _slewing = Metrics.CreateGauge("nina_dome_slewing", "1 if dome is slewing, else 0", new GaugeConfiguration { LabelNames = ln });
            _atPark = Metrics.CreateGauge("nina_dome_at_park", "1 if dome is at park, else 0", new GaugeConfiguration { LabelNames = ln });
            _atHome = Metrics.CreateGauge("nina_dome_at_home", "1 if dome is at home, else 0", new GaugeConfiguration { LabelNames = ln });
            _shutterOpen = Metrics.CreateGauge("nina_dome_shutter_open", "1 if shutter status is ShutterOpen, else 0", new GaugeConfiguration { LabelNames = ln });
            _shutterState = Metrics.CreateGauge("nina_dome_shutter_state", "Raw ShutterState enum value", new GaugeConfiguration { LabelNames = ln });
        }

        public void Subscribe() => _mediator.RegisterConsumer(this);

        public void UpdateDeviceInfo(DomeInfo info)
        {
            if (info == null || !info.Connected) return;
            var lv = _factory.LabelValues();
            if (!double.IsNaN(info.Azimuth)) _azimuth.WithLabels(lv).Set(info.Azimuth);
            _slewing.WithLabels(lv).Set(info.Slewing ? 1 : 0);
            _atPark.WithLabels(lv).Set(info.AtPark ? 1 : 0);
            _atHome.WithLabels(lv).Set(info.AtHome ? 1 : 0);
            _shutterOpen.WithLabels(lv).Set(info.ShutterStatus == ShutterState.ShutterOpen ? 1 : 0);
            _shutterState.WithLabels(lv).Set((int)info.ShutterStatus);
        }

        public void Dispose()
        {
            _mediator.RemoveConsumer(this);
            GC.SuppressFinalize(this);
        }
    }
}
