// Generated By: Claude Code (Claude Opus 4.7)
using NINA.Equipment.Interfaces.Mediator;
using Prometheus;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace NINA.Plugin.PrometheusExporter.Stream
{

    internal sealed class EquipmentMetrics : IMetricCollector
    {
        private readonly MetricFactory _factory;
        private readonly Gauge _gauge;

        private readonly ICameraMediator _camera;
        private readonly ITelescopeMediator _telescope;
        private readonly IFocuserMediator _focuser;
        private readonly IFilterWheelMediator _filterWheel;
        private readonly IGuiderMediator _guider;
        private readonly IDomeMediator _dome;
        private readonly IRotatorMediator _rotator;
        private readonly IFlatDeviceMediator _flat;
        private readonly ISafetyMonitorMediator _safety;
        private readonly IWeatherDataMediator _weather;
        private readonly ISwitchMediator _switch;

        // Stored handlers so Dispose can unsubscribe.
        private readonly List<Action> _unsubs = new();

        public EquipmentMetrics(
            MetricFactory factory,
            ICameraMediator camera,
            ITelescopeMediator telescope,
            IFocuserMediator focuser,
            IFilterWheelMediator filterWheel,
            IGuiderMediator guider,
            IDomeMediator dome,
            IRotatorMediator rotator,
            IFlatDeviceMediator flat,
            ISafetyMonitorMediator safety,
            IWeatherDataMediator weather,
            ISwitchMediator @switch)
        {
            _factory = factory;
            _camera = camera; _telescope = telescope; _focuser = focuser;
            _filterWheel = filterWheel; _guider = guider; _dome = dome;
            _rotator = rotator; _flat = flat; _safety = safety;
            _weather = weather; _switch = @switch;

            _gauge = Metrics.CreateGauge(
                "nina_equipment",
                "1 if equipment of the given type is connected, else 0",
                new GaugeConfiguration { LabelNames = _factory.LabelNames("type") });
        }

        public void Subscribe()
        {
            Wire(_camera, "camera");
            Wire(_telescope, "telescope");
            Wire(_focuser, "focuser");
            Wire(_filterWheel, "filterwheel");
            Wire(_guider, "guider");
            Wire(_dome, "dome");
            Wire(_rotator, "rotator");
            Wire(_flat, "flat_device");
            Wire(_safety, "safety_monitor");
            Wire(_weather, "weather");
            Wire(_switch, "switch");
        }

        private void Wire<THandler, TConsumer, TInfo>(
            IDeviceMediator<THandler, TConsumer, TInfo> mediator,
            string type)
            where THandler : NINA.Equipment.Interfaces.ViewModel.IDeviceVM<TInfo>
            where TConsumer : NINA.Equipment.Interfaces.Mediator.IDeviceConsumer<TInfo>
        {

            Func<object, EventArgs, Task> onConnected = (_, __) =>
            {
                _gauge.WithLabels(_factory.LabelValues(type)).Set(1);
                return Task.CompletedTask;
            };
            Func<object, EventArgs, Task> onDisconnected = (_, __) =>
            {
                _gauge.WithLabels(_factory.LabelValues(type)).Set(0);
                return Task.CompletedTask;
            };

            mediator.Connected += onConnected;
            mediator.Disconnected += onDisconnected;
            _unsubs.Add(() => mediator.Connected -= onConnected);
            _unsubs.Add(() => mediator.Disconnected -= onDisconnected);
        }

        public void Dispose()
        {
            foreach (var u in _unsubs)
            {
                try { u(); } catch { /* swallow on shutdown */ }
            }
            _unsubs.Clear();
            GC.SuppressFinalize(this);
        }
    }
}
