// Generated By: Claude Code (Claude Opus 4.7)
using NINA.Equipment.Equipment.MyFocuser;
using NINA.Equipment.Interfaces.Mediator;
using OxyPlot;
using Prometheus;
using System;

namespace NINA.Plugin.PrometheusExporter.Stream
{

    // Focuser temperature + position live here. AutoFocusMetrics owns the AF state-machine callbacks.
    // Both classes implement IFocuserConsumer and register independently with IFocuserMediator.
    internal sealed class FocuserMetrics : IMetricCollector, IFocuserConsumer
    {
        private readonly MetricFactory _factory;
        private readonly IFocuserMediator _mediator;
        private readonly Gauge _position;
        private readonly Gauge _temperature;

        public FocuserMetrics(MetricFactory factory, IFocuserMediator mediator)
        {
            _factory = factory;
            _mediator = mediator;
            _position = Metrics.CreateGauge(
                "nina_focuser_position",
                "Focuser position (steps)",
                new GaugeConfiguration { LabelNames = _factory.LabelNames() });
            _temperature = Metrics.CreateGauge(
                "nina_focuser_temperature_celsius",
                "Focuser ambient temperature in degrees Celsius",
                new GaugeConfiguration { LabelNames = _factory.LabelNames() });
        }

        public void Subscribe() => _mediator.RegisterConsumer(this);

        public void UpdateDeviceInfo(FocuserInfo info)
        {
            if (info == null || !info.Connected) return;
            var lv = _factory.LabelValues();
            _position.WithLabels(lv).Set(info.Position);
            if (!double.IsNaN(info.Temperature))
                _temperature.WithLabels(lv).Set(info.Temperature);
        }

        // No-op IFocuserConsumer callbacks owned by AutoFocusMetrics:
        public void UpdateEndAutoFocusRun(AutoFocusInfo info) { }
        public void UpdateUserFocused(FocuserInfo info) { }
        public void AutoFocusRunStarting() { }
        public void NewAutoFocusPoint(DataPoint dataPoint) { }

        public void Dispose()
        {
            _mediator.RemoveConsumer(this);
            GC.SuppressFinalize(this);
        }
    }
}
