// Generated By: Claude Code (Claude Opus 4.7)
using System;

namespace NINA.Plugin.PrometheusExporter.Stream
{

    internal interface IMetricCollector : IDisposable
    {
        void Subscribe();
    }
}
