// Generated By: Claude Code (Claude Opus 4.7)
using NINA.Core.Enum;
using NINA.Equipment.Equipment.MyTelescope;
using NINA.Equipment.Interfaces.Mediator;
using Prometheus;
using System;
using System.Threading.Tasks;

namespace NINA.Plugin.PrometheusExporter.Stream
{

    internal sealed class MountMetrics : IMetricCollector, ITelescopeConsumer
    {
        private readonly MetricFactory _factory;
        private readonly ITelescopeMediator _mediator;

        private readonly Gauge _altitude;
        private readonly Gauge _azimuth;
        private readonly Gauge _ra;
        private readonly Gauge _dec;
        private readonly Gauge _sideOfPier;        // -1=Unknown, 0=East, 1=West (encode 0=Unknown for Prom: use 0/1/2)
        private readonly Gauge _tracking;
        private readonly Gauge _slewing;
        private readonly Gauge _parked;
        private readonly Gauge _meridianFlip;
        private readonly Counter _sopUnknown;

        private PierSide _lastSop = PierSide.pierUnknown;
        private bool _initializedSop;

        public MountMetrics(MetricFactory factory, ITelescopeMediator mediator)
        {
            _factory = factory;
            _mediator = mediator;

            var ln = _factory.LabelNames();
            _altitude = Metrics.CreateGauge("nina_mount_altitude_degrees", "Mount altitude in degrees", new GaugeConfiguration { LabelNames = ln });
            _azimuth = Metrics.CreateGauge("nina_mount_azimuth_degrees", "Mount azimuth in degrees", new GaugeConfiguration { LabelNames = ln });
            _ra = Metrics.CreateGauge("nina_mount_ra_hours", "Mount RA in hours", new GaugeConfiguration { LabelNames = ln });
            _dec = Metrics.CreateGauge("nina_mount_dec_degrees", "Mount Dec in degrees", new GaugeConfiguration { LabelNames = ln });
            _sideOfPier = Metrics.CreateGauge("nina_mount_side_of_pier", "Mount side of pier (0=Unknown, 1=East, 2=West)", new GaugeConfiguration { LabelNames = ln });
            _tracking = Metrics.CreateGauge("nina_mount_tracking", "1 if tracking enabled, else 0", new GaugeConfiguration { LabelNames = ln });
            _slewing = Metrics.CreateGauge("nina_mount_slewing", "1 if currently slewing, else 0", new GaugeConfiguration { LabelNames = ln });
            _parked = Metrics.CreateGauge("nina_mount_parked", "1 if parked, else 0", new GaugeConfiguration { LabelNames = ln });
            _meridianFlip = Metrics.CreateGauge("nina_mount_meridian_flip", "1 between BeforeMeridianFlip and AfterMeridianFlip events, else 0", new GaugeConfiguration { LabelNames = ln });

            _sopUnknown = Metrics.CreateCounter(
                "nina_mount_side_of_pier_unknown_total",
                "Edge-triggered count of side-of-pier transitions into Unknown",
                new CounterConfiguration { LabelNames = ln });
        }

        public void Subscribe()
        {
            _mediator.RegisterConsumer(this);
            _mediator.BeforeMeridianFlip += OnBefore;
            _mediator.AfterMeridianFlip += OnAfter;
        }

        public void UpdateDeviceInfo(TelescopeInfo info)
        {
            if (info == null || !info.Connected) return;

            var lv = _factory.LabelValues();
            if (!double.IsNaN(info.Altitude)) _altitude.WithLabels(lv).Set(info.Altitude);
            if (!double.IsNaN(info.Azimuth)) _azimuth.WithLabels(lv).Set(info.Azimuth);
            if (!double.IsNaN(info.RightAscension)) _ra.WithLabels(lv).Set(info.RightAscension);
            if (!double.IsNaN(info.Declination)) _dec.WithLabels(lv).Set(info.Declination);

            _tracking.WithLabels(lv).Set(info.TrackingEnabled ? 1 : 0);
            _slewing.WithLabels(lv).Set(info.Slewing ? 1 : 0);
            _parked.WithLabels(lv).Set(info.AtPark ? 1 : 0);

            UpdateSideOfPier(info.SideOfPier, lv);
        }

        // Visible for testing.
        internal void UpdateSideOfPier(PierSide sop, string[] lv)
        {
            _sideOfPier.WithLabels(lv).Set(sop switch
            {
                PierSide.pierEast => 1,
                PierSide.pierWest => 2,
                _ => 0
            });
            if (sop == PierSide.pierUnknown && _initializedSop && _lastSop != PierSide.pierUnknown)
                _sopUnknown.WithLabels(lv).Inc();
            _lastSop = sop;
            _initializedSop = true;
        }

        private Task OnBefore(object sender, BeforeMeridianFlipEventArgs args)
        {
            _meridianFlip.WithLabels(_factory.LabelValues()).Set(1);
            return Task.CompletedTask;
        }

        private Task OnAfter(object sender, AfterMeridianFlipEventArgs args)
        {
            _meridianFlip.WithLabels(_factory.LabelValues()).Set(0);
            return Task.CompletedTask;
        }

        public void Dispose()
        {
            _mediator.BeforeMeridianFlip -= OnBefore;
            _mediator.AfterMeridianFlip -= OnAfter;
            _mediator.RemoveConsumer(this);
            GC.SuppressFinalize(this);
        }
    }
}
