// Generated By: Claude Code (Claude Opus 4.7)
using NINA.Equipment.Equipment.MySwitch;
using NINA.Equipment.Interfaces.Mediator;
using Prometheus;
using System;

namespace NINA.Plugin.PrometheusExporter.Stream
{

    internal sealed class SwitchMetrics : IMetricCollector, ISwitchConsumer
    {
        private readonly MetricFactory _factory;
        private readonly ISwitchMediator _mediator;

        private readonly Gauge _value;
        private readonly Gauge _writable;
        private readonly Gauge _targetValue;
        private readonly Gauge _min;
        private readonly Gauge _max;
        private readonly Gauge _stepSize;

        public SwitchMetrics(MetricFactory factory, ISwitchMediator mediator)
        {
            _factory = factory;
            _mediator = mediator;

            var ln = _factory.LabelNames(Constants.LabelId, Constants.LabelName);
            _value = Metrics.CreateGauge("nina_switch_value", "Current value of the named switch (readonly + writable)", new GaugeConfiguration { LabelNames = ln });
            _writable = Metrics.CreateGauge("nina_switch_writable", "1 if the switch is writable, 0 if readonly", new GaugeConfiguration { LabelNames = ln });
            _targetValue = Metrics.CreateGauge("nina_switch_target_value", "Target value of a writable switch", new GaugeConfiguration { LabelNames = ln });
            _min = Metrics.CreateGauge("nina_switch_min", "Minimum value of a writable switch", new GaugeConfiguration { LabelNames = ln });
            _max = Metrics.CreateGauge("nina_switch_max", "Maximum value of a writable switch", new GaugeConfiguration { LabelNames = ln });
            _stepSize = Metrics.CreateGauge("nina_switch_step_size", "Step size of a writable switch", new GaugeConfiguration { LabelNames = ln });
        }

        public void Subscribe() => _mediator.RegisterConsumer(this);

        public void UpdateDeviceInfo(SwitchInfo info)
        {
            if (info == null || !info.Connected) return;

            if (info.ReadonlySwitches != null)
            {
                foreach (var s in info.ReadonlySwitches)
                {
                    if (s == null) continue;
                    var lv = _factory.LabelValues(s.Id.ToString(), s.Name ?? Constants.Unknown);
                    _value.WithLabels(lv).Set(s.Value);
                    _writable.WithLabels(lv).Set(0);
                }
            }

            if (info.WritableSwitches != null)
            {
                foreach (var s in info.WritableSwitches)
                {
                    if (s == null) continue;
                    var lv = _factory.LabelValues(s.Id.ToString(), s.Name ?? Constants.Unknown);
                    _value.WithLabels(lv).Set(s.Value);
                    _writable.WithLabels(lv).Set(1);
                    _targetValue.WithLabels(lv).Set(s.TargetValue);
                    _min.WithLabels(lv).Set(s.Minimum);
                    _max.WithLabels(lv).Set(s.Maximum);
                    _stepSize.WithLabels(lv).Set(s.StepSize);
                }
            }
        }

        public void Dispose()
        {
            _mediator.RemoveConsumer(this);
            GC.SuppressFinalize(this);
        }
    }
}
