// Generated By: Claude Code (Claude Opus 4.7)
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: InternalsVisibleTo("NINA.Plugin.PrometheusExporter.Tests")]

[assembly: Guid("7081dfb8-dc05-4bde-9810-bbba1afe8430")]

// SemVer 3-segment for AssemblyVersion (.NET binding).
[assembly: AssemblyVersion("0.1.0")]
// 4-segment required by NINA's PluginLoader (constructs System.Version with all 4 components,
// rejects negative revision). Trailing .0 is a fixed build segment, not exposed to users.
[assembly: AssemblyFileVersion("0.1.0.0")]

[assembly: AssemblyTitle("Prometheus Exporter")]
[assembly: AssemblyDescription("Exposes a Prometheus scrape endpoint for NINA metrics")]
[assembly: AssemblyCompany("Naveen Malik")]
[assembly: AssemblyProduct("Prometheus Exporter")]
[assembly: AssemblyCopyright("Copyright © 2026 Naveen Malik")]

// Conservative back-floor — bump only when a new API is genuinely needed (see spec §14).
[assembly: AssemblyMetadata("MinimumApplicationVersion", "3.0.0.0")]

[assembly: AssemblyMetadata("License", "Apache-2.0")]
[assembly: AssemblyMetadata("LicenseURL", "https://www.apache.org/licenses/LICENSE-2.0")]
[assembly: AssemblyMetadata("Repository", "https://github.com/jewzaam/nina-prometheus-exporter")]
[assembly: AssemblyMetadata("Homepage", "https://github.com/jewzaam/nina-prometheus-exporter")]
[assembly: AssemblyMetadata("Tags", "prometheus, grafana, metrics, monitoring")]
[assembly: AssemblyMetadata("ChangelogURL", "https://github.com/jewzaam/nina-prometheus-exporter/blob/main/CHANGELOG.md")]
[assembly: AssemblyMetadata("FeaturedImageURL", "")]
[assembly: AssemblyMetadata("ScreenshotURL", "")]
[assembly: AssemblyMetadata("AltScreenshotURL", "")]
[assembly: AssemblyMetadata("LongDescription", @"
Prometheus Exporter is a NINA plugin that exposes a Prometheus scrape endpoint for NINA metrics.

Exposed metrics cover: equipment connection state, sequence status, per-exposure telemetry (HFR, stars, RMS, ADU stats), autofocus reports (run state, R-squared, position, duration), guiding RMS and per-step pulses, mount position and tracking, camera temperature and cooler power, focuser position/temperature, filter wheel position, plus dome/rotator/flat panel/safety monitor/weather where present.

The endpoint defaults to http://0.0.0.0:9876/metrics. All settings (port, bind address, sequence poll cadence, autofocus timeout) are configurable in the plugin Options panel and apply without a NINA restart.

# Getting help #

File an issue at https://github.com/jewzaam/nina-prometheus-exporter/issues
")]

[assembly: ComVisible(false)]
[assembly: NeutralResourcesLanguage("en")]
