// Generated By: Claude Code (Claude Opus 4.7)
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: InternalsVisibleTo("NINA.Plugin.PrometheusExporter.Tests")]

[assembly: Guid("7081dfb8-dc05-4bde-9810-bbba1afe8430")]

// Always 4-segment per standards/dotnet/style.md and standards/dotnet/nina-plugin.md §3.
// NINA's PluginLoader requires 4 components on AssemblyFileVersion (rejects negative revision);
// AssemblyVersion mirrors the same format for consistency. The trailing .0 is a fixed build segment.
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.0")]

[assembly: AssemblyTitle("Prometheus Exporter")]
[assembly: AssemblyDescription("Exposes a Prometheus scrape endpoint for NINA metrics")]
[assembly: AssemblyCompany("Naveen Malik")]
[assembly: AssemblyProduct("Prometheus Exporter")]
[assembly: AssemblyCopyright("Copyright © 2026 Naveen Malik")]

// Matches the NINA.Plugin nuget version the plugin compiles against, per standards/dotnet/nina-plugin.md sec 10.4.
// Bump whenever the NINA.Plugin PackageReference floor changes.
[assembly: AssemblyMetadata("MinimumApplicationVersion", "3.2.0.9001")]

[assembly: AssemblyMetadata("License", "Apache-2.0")]
[assembly: AssemblyMetadata("LicenseURL", "https://www.apache.org/licenses/LICENSE-2.0")]
[assembly: AssemblyMetadata("Repository", "https://github.com/jewzaam/nina-prometheus-exporter")]
[assembly: AssemblyMetadata("Homepage", "https://github.com/jewzaam/nina-prometheus-exporter")]
[assembly: AssemblyMetadata("Tags", "prometheus, grafana, metrics, monitoring")]
[assembly: AssemblyMetadata("ChangelogURL", "https://github.com/jewzaam/nina-prometheus-exporter/blob/main/CHANGELOG.md")]
[assembly: AssemblyMetadata("FeaturedImageURL", "")]
[assembly: AssemblyMetadata("ScreenshotURL", "")]
[assembly: AssemblyMetadata("AltScreenshotURL", "")]
[assembly: AssemblyMetadata("LongDescription", @"
Prometheus Exporter is a NINA plugin that exposes a Prometheus scrape endpoint for NINA metrics.

Exposed metrics cover: equipment connection state, sequence status, per-exposure telemetry (HFR, stars, RMS, ADU stats), autofocus reports (run state, R-squared, position, duration), guiding RMS and per-step pulses, mount position and tracking, camera temperature and cooler power, focuser position/temperature, filter wheel position, plus dome/rotator/flat panel/safety monitor/weather where present.

The endpoint defaults to http://127.0.0.1:9876/metrics (loopback only). To expose on the LAN, change the Bind address in the plugin Options panel (e.g. 0.0.0.0 or a specific LAN IP). All settings (port, bind address, sequence poll cadence, autofocus timeout) are configurable in Options; Port/Bind changes take effect when you click Apply.

# Getting help #

File an issue at https://github.com/jewzaam/nina-prometheus-exporter/issues
")]

[assembly: ComVisible(false)]
[assembly: NeutralResourcesLanguage("en")]
