# Generated By: Claude Code (Claude Opus 4.7)
[CmdletBinding()]
param(
    [string]$SourceDir = 'bin\Release'
)

$ErrorActionPreference = 'Stop'

$match = Select-String -Path Properties/AssemblyInfo.cs -Pattern 'AssemblyVersion\("([0-9.]+)"\)'
if (-not $match) { Write-Error 'AssemblyVersion not found in Properties/AssemblyInfo.cs'; exit 1 }
$ver = $match.Matches.Groups[1].Value
# Name matches NINA's canonical github-action.yaml sample (<AssemblyName>.<X.Y.Z.B>.zip)
# so the URL path in manifest.json matches what other plugin authors do.
$zip = "NINA.Plugin.PrometheusExporter.$ver.zip"

# Resolves $ResolvedShipDlls (absolute paths); hard-fails on missing, warns on extras.
. (Join-Path $PSScriptRoot 'select-ship-dlls.ps1') -SourceDir $SourceDir

# Some shipped DLLs in our dependency graph carry pre-1980 LastWriteTime stamps that
# Compress-Archive's underlying System.IO.Compression rejects. Normalize before zipping.
$now = Get-Date
foreach ($path in $ResolvedShipDlls) {
    $file = Get-Item $path
    if ($file.LastWriteTime.Year -lt 1980) {
        $file.LastWriteTime = $now
    }
}

Compress-Archive -Path $ResolvedShipDlls -DestinationPath $zip -Force
Write-Output "Packaged $zip ($($ResolvedShipDlls.Count) DLLs)"
