# Generated By: Claude Code (Claude Opus 4.7)
[CmdletBinding()]
param(
    [string]$SourceDir = 'bin\Release'
)

$ErrorActionPreference = 'Stop'

$match = Select-String -Path Properties/AssemblyInfo.cs -Pattern 'AssemblyVersion\("([0-9.]+)"\)'
if (-not $match) { Write-Error 'AssemblyVersion not found in Properties/AssemblyInfo.cs'; exit 1 }
$ver = $match.Matches.Groups[1].Value
$zip = "nina-prometheus-exporter-$ver.zip"

if (-not (Test-Path $SourceDir)) {
    Write-Error "Source dir not found: $SourceDir. Run 'make build-release' first."
    exit 1
}

Compress-Archive -Path "$SourceDir\*.dll" -DestinationPath $zip -Force
Write-Output "Packaged $zip"
