# Generated By: Claude Code (Claude Opus 4.7)
# Emit manifest.json for the NINA plugin-manifests repo
# (https://github.com/isbeorn/nina.plugin.manifests).
#
# Inputs:
#   - Properties/AssemblyInfo.cs       : version + metadata attributes
#   - $env:GITHUB_REPOSITORY (CI)      : owner/name for Installer.URL fallback
#   - $env:GITHUB_REF_NAME   (CI)      : tag for Installer.URL fallback
#   - -InstallerUrl                    : explicit override
#   - <zip in bin/Release>             : checksummed for Installer.Checksum
#
# Output: manifest.json in the repo root.
[CmdletBinding()]
param(
    [string]$InstallerUrl,
    [string]$ZipPath
)

$ErrorActionPreference = 'Stop'

$assemblyInfo = 'Properties/AssemblyInfo.cs'
$content = Get-Content $assemblyInfo -Raw

function Get-Attr {
    param([string]$Pattern)
    if ($content -match $Pattern) { return $matches[1] }
    return $null
}

$ver = Get-Attr 'AssemblyVersion\("([0-9.]+)"\)'
if (-not $ver) { Write-Error "AssemblyVersion not found"; exit 1 }
$verParts = $ver.Split('.')
if ($verParts.Count -ne 4) { Write-Error "AssemblyVersion '$ver' is not 4-segment"; exit 1 }

$name = Get-Attr 'AssemblyTitle\("([^"]+)"\)'
$id = Get-Attr 'Guid\("([0-9a-fA-F\-]+)"\)'
$author = Get-Attr 'AssemblyCompany\("([^"]+)"\)'
$shortDesc = Get-Attr 'AssemblyDescription\("([^"]+)"\)'

function Get-Metadata {
    param([string]$Key)
    # Two patterns: regular string then verbatim @"..."
    $regular = "AssemblyMetadata\(`"$Key`",\s*`"([^`"]*)`"\)"
    if ($content -match $regular) { return $matches[1] }
    $verbatim = "AssemblyMetadata\(`"$Key`",\s*@`"([\s\S]*?)`"\)"
    if ($content -match $verbatim) { return $matches[1] }
    return $null
}

$homepage = Get-Metadata 'Homepage'
$repository = Get-Metadata 'Repository'
$license = Get-Metadata 'License'
$licenseUrl = Get-Metadata 'LicenseURL'
$changelogUrl = Get-Metadata 'ChangelogURL'
$featuredImageUrl = Get-Metadata 'FeaturedImageURL'
$screenshotUrl = Get-Metadata 'ScreenshotURL'
$altScreenshotUrl = Get-Metadata 'AltScreenshotURL'
$longDesc = Get-Metadata 'LongDescription'
$tagsRaw = Get-Metadata 'Tags'
$minApp = Get-Metadata 'MinimumApplicationVersion'

if (-not $minApp) { Write-Error "MinimumApplicationVersion not found"; exit 1 }
$minAppParts = $minApp.Split('.')
if ($minAppParts.Count -ne 4) { Write-Error "MinimumApplicationVersion '$minApp' is not 4-segment"; exit 1 }

$tags = @()
if ($tagsRaw) {
    $tags = $tagsRaw.Split(',') | ForEach-Object { $_.Trim() } | Where-Object { $_ }
}

if (-not $ZipPath) {
    $ZipPath = "NINA.Plugin.PrometheusExporter.$ver.zip"
}
if (-not (Test-Path $ZipPath)) {
    Write-Error "Zip not found: $ZipPath (run 'make build-package' first)"
    exit 1
}
# Use .NET directly instead of Get-FileHash; the latter fails on some
# Windows Server 2025 GitHub runners with "not recognized as cmdlet".
$sha256 = [System.Security.Cryptography.SHA256]::Create()
try {
    $stream = [System.IO.File]::OpenRead($ZipPath)
    try {
        $hashBytes = $sha256.ComputeHash($stream)
    }
    finally {
        $stream.Dispose()
    }
}
finally {
    $sha256.Dispose()
}
$hash = ([BitConverter]::ToString($hashBytes)).Replace('-', '')

if (-not $InstallerUrl) {
    $InstallerUrl = $env:INSTALLER_URL
}
if (-not $InstallerUrl) {
    $repo = $env:GITHUB_REPOSITORY
    $tag = $env:GITHUB_REF_NAME
    if ($repo -and $tag) {
        $InstallerUrl = "https://github.com/$repo/releases/download/$tag/$(Split-Path $ZipPath -Leaf)"
    }
    else {
        Write-Error "InstallerUrl not provided. Set -InstallerUrl, INSTALLER_URL env var, or GITHUB_REPOSITORY+GITHUB_REF_NAME."
        exit 1
    }
}

$manifest = [ordered]@{
    Name                      = $name
    Identifier                = $id
    Version                   = [ordered]@{
        Major = $verParts[0]
        Minor = $verParts[1]
        Patch = $verParts[2]
        Build = $verParts[3]
    }
    Author                    = $author
    Homepage                  = $homepage
    Repository                = $repository
    License                   = $license
    LicenseURL                = $licenseUrl
    ChangelogURL              = $changelogUrl
    Tags                      = $tags
    MinimumApplicationVersion = [ordered]@{
        Major = $minAppParts[0]
        Minor = $minAppParts[1]
        Patch = $minAppParts[2]
        Build = $minAppParts[3]
    }
    Descriptions              = [ordered]@{
        ShortDescription = $shortDesc
        LongDescription  = $longDesc
        FeaturedImageURL = $featuredImageUrl
        ScreenshotURL    = $screenshotUrl
        AltScreenshotURL = $altScreenshotUrl
    }
    Installer                 = [ordered]@{
        URL          = $InstallerUrl
        Type         = 'ARCHIVE'
        Checksum     = $hash
        ChecksumType = 'SHA256'
    }
}

$json = $manifest | ConvertTo-Json -Depth 10
$json | Out-File 'manifest.json' -Encoding utf8
Write-Output "Wrote manifest.json (Installer.URL=$InstallerUrl, sha256=$hash)"
