# Generated By: Claude Code (Claude Opus 4.7)
# Copy plugin DLLs to %LOCALAPPDATA%\NINA\Plugins\Prometheus Exporter\
[CmdletBinding()]
param(
    [string]$SourceDir = 'bin\Release',
    [string]$PluginDir = (Join-Path $env:LOCALAPPDATA 'NINA\Plugins\3.0.0\Prometheus Exporter')
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $SourceDir)) {
    Write-Error "Source dir not found: $SourceDir. Run 'make build-release' first."
    exit 1
}

New-Item -ItemType Directory -Force -Path $PluginDir | Out-Null

# Exclude NINA framework DLLs (shipped by NINA itself); copy everything else, including this plugin's own NINA.Plugin.PrometheusExporter.dll.
$ninaFrameworkDlls = @(
    'NINA.Core.dll',
    'NINA.Astrometry.dll',
    'NINA.Equipment.dll',
    'NINA.Image.dll',
    'NINA.MGEN.dll',
    'NINA.Plugin.dll',
    'NINA.Profile.dll',
    'NINA.Sequencer.dll',
    'NINA.Sequencer.Generators.dll',
    'NINA.WPF.Base.dll',
    'NINA.CustomControlLibrary.dll'
)

Get-ChildItem $SourceDir -Filter '*.dll' |
    Where-Object { $ninaFrameworkDlls -notcontains $_.Name } |
    Copy-Item -Destination $PluginDir -Force

Write-Output "Installed to $PluginDir"
Get-ChildItem $PluginDir -Filter '*.dll' | Select-Object Name
