# Generated By: Claude Code (Claude Opus 4.7)
# Copy plugin DLLs to %LOCALAPPDATA%\NINA\Plugins\3.0.0\Prometheus Exporter\
[CmdletBinding()]
param(
    [string]$SourceDir = 'bin\Release',
    [string]$PluginDir = (Join-Path $env:LOCALAPPDATA 'NINA\Plugins\3.0.0\Prometheus Exporter')
)

$ErrorActionPreference = 'Stop'

# Resolves $ResolvedShipDlls (absolute paths); hard-fails on missing, warns on extras.
. (Join-Path $PSScriptRoot 'select-ship-dlls.ps1') -SourceDir $SourceDir

New-Item -ItemType Directory -Force -Path $PluginDir | Out-Null
Copy-Item -Path $ResolvedShipDlls -Destination $PluginDir -Force

Write-Output "Installed $($ResolvedShipDlls.Count) DLLs to $PluginDir"
