# Generated By: Claude Code (Claude Opus 4.7)
# Stop any running NINA process so install can overwrite the locked plugin DLL.
Get-Process NINA -ErrorAction SilentlyContinue | Stop-Process -Force
Start-Sleep -Seconds 1
Write-Output "NINA stopped (or not running)"
