# Generated By: Claude Code (Claude Opus 4.7)
#
# Local orchestrator that submits this plugin's release manifest as a PR to
# https://github.com/isbeorn/nina.plugin.manifests
#
# Workflow:
#   1. Read AssemblyVersion from Properties/AssemblyInfo.cs.
#   2. Verify the GitHub release for that version exists and has manifest.json.
#   3. Download manifest.json from the release (authoritative copy, sha256 pins released zip).
#   4. Validate it against the upstream schema (via 'make test-manifest').
#   5. cd into $ManifestsRepoDir, confirm clean tree, sync main with the upstream remote.
#   6. Create branch prometheus-exporter/<version> (-B reuses existing branch).
#   7. Drop the manifest at manifests/p/Prometheus Exporter/manifest.<version>.json.
#   8. Commit + force-push branch to the user's fork (origin).
#   9. Open (or update) a PR from origin's branch against isbeorn/nina.plugin.manifests:main.
#
# Prerequisites:
#   - gh CLI authenticated as the fork owner.
#   - $ManifestsRepoDir is a clone of nina.plugin.manifests with TWO remotes:
#       * one pointing at isbeorn/nina.plugin.manifests (upstream)
#       * one pointing at <your-user>/nina.plugin.manifests (your fork)
#     Remote names don't matter -- the script discovers each by URL.
#   - npx + Node available (for the schema validation step).
#
# This script never touches credentials directly -- gh handles auth, git handles push.
[CmdletBinding()]
param(
    [string]$ManifestsRepoDir = (Join-Path $HOME 'source/nina.plugin.manifests'),
    [string]$PluginDir = 'manifests/p/Prometheus Exporter',
    [string]$UpstreamRepo = 'isbeorn/nina.plugin.manifests',
    [string]$BranchPrefix = 'prometheus-exporter'
)

$ErrorActionPreference = 'Stop'

function Assert-Cmd {
    param([string]$Name)
    if (-not (Get-Command $Name -ErrorAction SilentlyContinue)) {
        Write-Error "Required command not on PATH: $Name"
        exit 1
    }
}

Assert-Cmd 'gh'
Assert-Cmd 'git'

# --- 1. Read version
$match = Select-String -Path Properties/AssemblyInfo.cs -Pattern 'AssemblyVersion\("([0-9.]+)"\)'
if (-not $match) { Write-Error 'AssemblyVersion not found'; exit 1 }
$ver = $match.Matches.Groups[1].Value
Write-Output "Version: $ver"

# --- 2-3. Download manifest.json from this repo's release
$manifestPath = Join-Path (Get-Location) 'manifest.json'
if (Test-Path $manifestPath) { Remove-Item $manifestPath -Force }
Write-Output "Downloading manifest.json from release $ver..."
& gh release download $ver --pattern manifest.json --clobber
if ($LASTEXITCODE -ne 0) {
    Write-Error "Failed to download manifest.json from release $ver. Confirm the release exists and you are authenticated to the correct repo."
    exit 1
}

# --- 4. Validate
Write-Output "Validating manifest against upstream schema..."
& make test-manifest
if ($LASTEXITCODE -ne 0) {
    Write-Error "manifest.json failed schema validation"
    exit 1
}

# --- 5. cd to manifests repo, verify state
if (-not (Test-Path $ManifestsRepoDir)) {
    Write-Error "Manifests repo not found at $ManifestsRepoDir. Clone <owner>/nina.plugin.manifests there or pass -ManifestsRepoDir."
    exit 1
}
$manifestPathAbs = (Resolve-Path $manifestPath).Path

Push-Location $ManifestsRepoDir
try {
    $status = & git status --porcelain
    if ($status) {
        Write-Error "Manifests repo not clean: $ManifestsRepoDir"
        exit 1
    }

    # Discover upstream + fork remotes from URLs rather than naming convention.
    # Upstream = the remote pointing at $UpstreamRepo (isbeorn/nina.plugin.manifests).
    # Fork     = any other remote pointing at <owner>/nina.plugin.manifests where owner != isbeorn.
    $remoteNames = @((& git remote) -split "`r?`n" | Where-Object { $_ })
    $UpstreamRemote = $null
    $ForkRemote = $null
    $ForkOwner = $null
    foreach ($r in $remoteNames) {
        $url = (& git remote get-url $r).Trim()
        if ($url -match "[:/](?<owner>[^/]+)/nina\.plugin\.manifests(\.git)?$") {
            $owner = $matches['owner']
            if ($owner -ieq 'isbeorn') {
                $UpstreamRemote = $r
            }
            elseif (-not $ForkRemote) {
                $ForkRemote = $r
                $ForkOwner = $owner
            }
        }
    }
    if (-not $UpstreamRemote) {
        Write-Error "No remote points at $UpstreamRepo in $ManifestsRepoDir. Add one with: git remote add upstream https://github.com/$UpstreamRepo.git"
        exit 1
    }
    if (-not $ForkRemote) {
        Write-Error "No fork remote found (a remote pointing at <user>/nina.plugin.manifests, owner != isbeorn) in $ManifestsRepoDir."
        exit 1
    }
    Write-Output "Remotes: upstream='$UpstreamRemote', fork='$ForkRemote' (owner=$ForkOwner)"

    # Sync main with upstream
    Write-Output "Syncing main with $UpstreamRemote..."
    & git fetch $UpstreamRemote main
    if ($LASTEXITCODE -ne 0) { exit 1 }
    & git checkout main
    if ($LASTEXITCODE -ne 0) { exit 1 }
    & git reset --hard "$UpstreamRemote/main"
    if ($LASTEXITCODE -ne 0) { exit 1 }

    # --- 6. Branch
    $branch = "$BranchPrefix/$ver"
    Write-Output "Creating branch $branch..."
    & git checkout -B $branch
    if ($LASTEXITCODE -ne 0) { exit 1 }

    # --- 7. Drop manifest
    $destDir = $PluginDir
    if (-not (Test-Path $destDir)) {
        New-Item -ItemType Directory -Force -Path $destDir | Out-Null
    }
    $destFile = Join-Path $destDir "manifest.$ver.json"
    Copy-Item $manifestPathAbs $destFile -Force
    Write-Output "Copied manifest to $destFile"

    # --- 8. Commit + push
    & git add -- $destFile
    if ($LASTEXITCODE -ne 0) { exit 1 }

    $staged = & git diff --staged --name-only
    if (-not $staged) {
        Write-Output "No changes vs upstream; manifest already merged. Nothing to PR."
        exit 0
    }

    & git commit -m "Add Prometheus Exporter $ver"
    if ($LASTEXITCODE -ne 0) { exit 1 }

    Write-Output "Pushing $branch to $ForkRemote..."
    & git push --force-with-lease $ForkRemote $branch
    if ($LASTEXITCODE -ne 0) { exit 1 }

    # --- 9. Open or update PR
    $headRef = "${ForkOwner}:${branch}"
    $existing = & gh pr list --repo $UpstreamRepo --head $headRef --json number --jq '.[0].number'

    if ($existing) {
        Write-Output "PR #$existing already open against $UpstreamRepo for $headRef. Push updated the branch."
    }
    else {
        $body = "Automated manifest submission for [Prometheus Exporter $ver](https://github.com/jewzaam/nina-prometheus-exporter/releases/tag/$ver)."
        & gh pr create `
            --repo $UpstreamRepo `
            --head $headRef `
            --base main `
            --title "Add Prometheus Exporter $ver" `
            --body $body
        if ($LASTEXITCODE -ne 0) { exit 1 }
        Write-Output "PR opened against $UpstreamRepo."
    }
}
finally {
    Pop-Location
}
