# Generated By: Claude Code (Claude Opus 4.7)
[CmdletBinding()]
param(
    [string]$NinaExe = "C:\Program Files\N.I.N.A. - Nighttime Imaging 'N' Astronomy\NINA.exe"
)

Get-Process NINA -ErrorAction SilentlyContinue | Stop-Process -Force
Start-Sleep -Seconds 1
Start-Process $NinaExe
Write-Output "Launched NINA"
