# Generated By: Claude Code (Claude Opus 4.7)
#
# Resolves the absolute paths of every DLL to ship from a source directory.
# Hard-fails if any DLL listed in ship-list.ps1 is missing from the source dir
# (catches refactor regressions: a renamed/dropped dep would silently break runtime).
# Warns on DLLs in the source dir that are neither in the ship list nor bundled by
# NINA's install -- those are the ones genuinely new and unaccounted for.
#
# Sourced (dot-imported) by install.ps1 and build-package.ps1. Exports $ResolvedShipDlls.
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$SourceDir
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'ship-list.ps1')

if (-not (Test-Path $SourceDir)) {
    Write-Error "Source dir not found: $SourceDir. Run 'make build-release' first."
    exit 1
}

$present = @(Get-ChildItem $SourceDir -Filter '*.dll' | ForEach-Object { $_.Name })

# Hard-fail on missing ship DLLs.
$missing = $ShipDlls | Where-Object { $present -notcontains $_ }
if ($missing) {
    Write-Error ("Missing required DLLs from $($SourceDir):" + [Environment]::NewLine + ($missing -join [Environment]::NewLine))
    exit 1
}

# Warn on truly-unaccounted DLLs: in bin/Release, not shipped, not bundled by NINA.
$ninaBundled = Get-NinaBundledDllSet
if ($ninaBundled.Count -eq 0) {
    Write-Warning "NINA install not found in standard locations -- cannot verify which bin/Release DLLs are already shipped by NINA. Skipping the 'extras' check."
} else {
    $extras = $present | Where-Object {
        ($ShipDlls -notcontains $_) -and ($ninaBundled -notcontains $_)
    }
    if ($extras) {
        Write-Warning ("DLLs in $($SourceDir) that are neither shipped by this plugin nor bundled by NINA:" + [Environment]::NewLine + ($extras -join [Environment]::NewLine) + [Environment]::NewLine + "If any are runtime-required, add to scripts/ship-list.ps1.")
    }
}

$ResolvedShipDlls = $ShipDlls | ForEach-Object { Join-Path $SourceDir $_ }
