# Generated By: Claude Code (Claude Opus 4.7)
#
# Single source of truth for which DLLs ship in the plugin install dir.
#
# Rationale: building this plugin pulls ~84 transitive DLLs into bin/Release because
# the NINA.Plugin nuget references the entire NINA framework + its deps. 71 of those
# duplicate what NINA itself already ships in its install dir. We must ship ONLY:
#   1. The plugin assembly itself.
#   2. Direct deps not already in NINA (prometheus-net, EmbedIO).
#   3. Transitive deps of #2 not already in NINA.
#
# If you add a PackageReference to the csproj that pulls a new runtime assembly,
# add it here too. install.ps1 / build-package.ps1 will hard-fail if a listed DLL
# is missing from bin/Release, and warn if bin/Release contains an unlisted *.dll
# that is also NOT present in NINA's install dir (so a genuinely new dep that NINA
# does not bundle gets flagged for review -- anything NINA already bundles is silent).

$ShipDlls = @(
    # Plugin itself
    'NINA.Plugin.PrometheusExporter.dll',

    # prometheus-net (metric registry + text formatter)
    'Prometheus.NetStandard.dll',

    # EmbedIO HTTP transport (bypasses http.sys URL ACL on non-loopback binds)
    'EmbedIO.dll',
    'Swan.Lite.dll',

    # Microsoft.Extensions.* -- transitively required by EmbedIO
    'Microsoft.Extensions.Configuration.Abstractions.dll',
    'Microsoft.Extensions.Configuration.Binder.dll',
    'Microsoft.Extensions.Configuration.dll',
    'Microsoft.Extensions.Http.dll',
    'Microsoft.Extensions.Logging.Abstractions.dll',
    'Microsoft.Extensions.Logging.dll',
    'Microsoft.Extensions.ObjectPool.dll',
    'Microsoft.Extensions.Options.dll',
    'Microsoft.Extensions.Primitives.dll'
)

# Returns the set of DLL filenames NINA itself ships, read from the NINA install dir.
# If NINA isn't installed at the expected path, returns an empty list and select-ship-dlls.ps1
# will warn about that separately (any unlisted DLL will then be flagged for review).
function Get-NinaBundledDllSet {
    $candidates = @(
        "C:\Program Files\N.I.N.A. - Nighttime Imaging 'N' Astronomy",
        "C:\Program Files (x86)\N.I.N.A. - Nighttime Imaging 'N' Astronomy"
    )
    foreach ($dir in $candidates) {
        if (Test-Path $dir) {
            return @(Get-ChildItem $dir -Filter '*.dll' | ForEach-Object { $_.Name })
        }
    }
    return @()
}
