# Generated By: Claude Code (Claude Opus 4.7)
# Validate Properties/AssemblyInfo.cs version metadata.
# 1. AssemblyVersion + AssemblyFileVersion both present, format X.Y.Z.0, and equal.
# 2. If $env:BASE_REF is set (CI on PR), version differs from origin/$BASE_REF.
# See docs/superpowers/specs/2026-05-18-versioning.md for the deviation rationale.
[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

$assemblyInfo = 'Properties/AssemblyInfo.cs'
if (-not (Test-Path $assemblyInfo)) {
    Write-Error "Missing $assemblyInfo"
    exit 1
}

function Get-Attr {
    param([string]$Attr, [string]$Path)
    $match = Select-String -Path $Path -Pattern "$Attr\(`"([0-9.]+)`"\)"
    if (-not $match) {
        Write-Error "$Attr not found in $Path"
        exit 1
    }
    $match.Matches.Groups[1].Value
}

$av = Get-Attr 'AssemblyVersion' $assemblyInfo
$afv = Get-Attr 'AssemblyFileVersion' $assemblyInfo

$pattern = '^[0-9]+\.[0-9]+\.[0-9]+\.0$'
if ($av -notmatch $pattern) {
    Write-Error "AssemblyVersion '$av' does not match X.Y.Z.0"
    exit 1
}
if ($afv -notmatch $pattern) {
    Write-Error "AssemblyFileVersion '$afv' does not match X.Y.Z.0"
    exit 1
}
if ($av -ne $afv) {
    Write-Error "AssemblyVersion ($av) != AssemblyFileVersion ($afv)"
    exit 1
}

Write-Output "Version OK: $av (format + sources match)"

$baseRef = $env:BASE_REF
if ([string]::IsNullOrEmpty($baseRef)) {
    Write-Output "BASE_REF not set; skipping bump check."
    exit 0
}

$baseContent = git show "origin/${baseRef}:$assemblyInfo" 2>$null
if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrEmpty($baseContent)) {
    Write-Output "Could not read origin/${baseRef}:${assemblyInfo}; skipping bump check."
    exit 0
}

if ($baseContent -match 'AssemblyVersion\("([0-9.]+)"\)') {
    $baseAv = $matches[1]
    if ($baseAv -eq $av) {
        Write-Error "AssemblyVersion not bumped (still $av on origin/$baseRef)"
        exit 1
    }
    Write-Output "Version bumped: origin/$baseRef = $baseAv -> head = $av"
}
else {
    Write-Output "No AssemblyVersion on origin/$baseRef; treating as initial release."
}
