# Generated By: Claude Code (Claude Opus 4.7)
# Preflight env check for the Prometheus Exporter plugin build.
# In CI ($env:CI=true) only validates the .NET SDK; NINA install + plugins dir checks are dev-only.
[CmdletBinding()]
param(
    [string]$DotnetExe   = 'C:\Program Files\dotnet\dotnet.exe',
    [string]$NinaExe     = "C:\Program Files\N.I.N.A. - Nighttime Imaging 'N' Astronomy\NINA.exe",
    [string]$PluginDir   = (Join-Path $env:LOCALAPPDATA 'NINA\Plugins\Prometheus Exporter')
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $DotnetExe)) {
    $resolved = Get-Command dotnet -ErrorAction SilentlyContinue
    if ($resolved) {
        $DotnetExe = $resolved.Source
    }
    else {
        Write-Error "dotnet not found (looked at $DotnetExe and PATH)"
        exit 1
    }
}

$sdks = & $DotnetExe --list-sdks
if (-not ($sdks -match '^8\.')) {
    Write-Error ".NET 8 SDK not installed. Found: $sdks"
    exit 1
}

if ($env:CI -eq 'true') {
    Write-Output "env OK (CI mode; NINA checks skipped)"
    Write-Output "  .NET SDKs: $($sdks -join ', ')"
    Write-Output "  dotnet:    $DotnetExe"
    exit 0
}

if (-not (Test-Path $NinaExe)) {
    Write-Error "NINA not installed at $NinaExe"
    exit 1
}

if (-not (Test-Path $PluginDir)) {
    New-Item -ItemType Directory -Force -Path $PluginDir | Out-Null
}

Write-Output "env OK"
Write-Output "  .NET SDKs: $($sdks -join ', ')"
Write-Output "  NINA:      $NinaExe"
Write-Output "  Plugins:   $PluginDir"
