# Generated By: Claude Code (Claude Opus 4.7)
# Preflight env check for the Prometheus Exporter plugin build.
[CmdletBinding()]
param(
    [string]$DotnetExe   = 'C:\Program Files\dotnet\dotnet.exe',
    [string]$NinaExe     = "C:\Program Files\N.I.N.A. - Nighttime Imaging 'N' Astronomy\NINA.exe",
    [string]$PluginDir   = (Join-Path $env:LOCALAPPDATA 'NINA\Plugins\Prometheus Exporter')
)

$ErrorActionPreference = 'Stop'

if (-not (Test-Path $DotnetExe)) {
    Write-Error "dotnet not found at $DotnetExe"
    exit 1
}

$sdks = & $DotnetExe --list-sdks
if (-not ($sdks -match '^8\.')) {
    Write-Error ".NET 8 SDK not installed. Found: $sdks"
    exit 1
}

if (-not (Test-Path $NinaExe)) {
    Write-Error "NINA not installed at $NinaExe"
    exit 1
}

if (-not (Test-Path $PluginDir)) {
    New-Item -ItemType Directory -Force -Path $PluginDir | Out-Null
}

Write-Output "env OK"
Write-Output "  .NET SDKs: $($sdks -join ', ')"
Write-Output "  NINA:      $NinaExe"
Write-Output "  Plugins:   $PluginDir"
