# Generated By: Claude Code (Claude Opus 4.7)
[CmdletBinding()]
param(
    [string]$PluginDir = (Join-Path $env:LOCALAPPDATA 'NINA\Plugins\3.0.0\Prometheus Exporter'),
    [string]$LegacyDir = (Join-Path $env:LOCALAPPDATA 'NINA\Plugins\Prometheus Exporter')
)

$removed = $false
foreach ($p in @($PluginDir, $LegacyDir)) {
    if (Test-Path $p) {
        Remove-Item -Recurse -Force $p
        Write-Output "Removed $p"
        $removed = $true
    }
}
if (-not $removed) {
    Write-Output "Nothing to uninstall"
}
